---
kind: pipeline
name: "Test in 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 3.6"
    image: erotemic/research:PY_VER_3.6
    commands:
      - . $HOME/.local/conda/etc/profile.d/conda.sh
