---
kind: pipeline
name: "Test kwplot in 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 3.6"
    image: python:3.6
    commands:
      - pip install pip setuptools -U
      - pip install git+ssh://git@gitlab.kitware.com/vigilant/kwarray.git@dev/0.4.0#egg=kwarray
      - pip install -r requirements.txt -U
      - python setup.py develop
      - ./run_tests.py
      # - pip install -v --no-use-pep517 .
      #- pytest -x --pyargs kwimage  # using pyargs tests the installed package instead of the source one

    volumes:
      - name: ssh
        path: /root/.ssh

trigger:
  event:
    - pull_request
    - tag

volumes:
  - name: ssh
    host:
      path: /home/vigilant-robot/.ssh

