# Note: expand yaml
# yaml merge-expand .gitlab-ci.yml _expandyml && cat _expandyml
# 
# GITLAB LINTER
# https://gitlab.kitware.com/computer-vision/kwimage/-/ci/lint


# This CI file has 4 types of jobs:
# (1) in the build stage we we build the wheels on a manylinux docker image
# (2) then in the test stage we install the wheels, run unit tests, and measure coverage
# (3) after testing we sign the wheels with the CI's GPG key
# (4) finally if we are on the release branch we will push the signed wheels to pypi

stages:
  - build
  - test
  - gpgsign
  - deploy


.__gpg_heredoc__: &__gpg_heredoc__
        - | 
            # THIS IS NOT EXECUTE ON THE CI, THIS IS FOR DEVELOPER REFERENCE
            # ON HOW THE ENCRYPTED GPG KEYS ARE SETUP.
            
            # Load or generate secrets
            load_secrets
            echo $CI_KITWARE_SECRET
            echo $TWINE_USERNAME

            # ADD RELEVANT VARIABLES TO GITLAB SECRET VARIABLES
            # https://gitlab.kitware.com/computer-vision/kwarray/-/settings/ci_cd
            # Note that it is important to make sure that these variables are
            # only decrpyted on protected branches by selecting the protected
            # and masked option. Also make sure you have master and release
            # branches protected.
            # https://gitlab.kitware.com/computer-vision/kwarray/-/settings/repository#js-protected-branches-settings

            # HOW TO ENCRYPT YOUR SECRET GPG KEY
            IDENTIFIER="travis-ci-Erotemic"
            GPG_KEYID=$(gpg --list-keys --keyid-format LONG "$IDENTIFIER" | head -n 2 | tail -n 1 | awk '{print $1}' | tail -c 9)
            echo "GPG_KEYID = $GPG_KEYID"

            # Export plaintext gpg public keys, private keys, and trust info
            mkdir -p dev
            gpg --armor --export-secret-keys $GPG_KEYID > dev/ci_secret_gpg_key.pgp
            gpg --armor --export $GPG_KEYID > dev/ci_public_gpg_key.pgp
            gpg --export-ownertrust > dev/gpg_owner_trust

            # Encrypt gpg keys and trust with CI secret
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/ci_public_gpg_key.pgp > dev/ci_public_gpg_key.pgp.enc
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/ci_secret_gpg_key.pgp > dev/ci_secret_gpg_key.pgp.enc
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/gpg_owner_trust > dev/gpg_owner_trust.enc
            echo $GPG_KEYID > dev/public_gpg_key

            # Test decrpyt
            cat dev/public_gpg_key
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc 
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc 
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc 

            unload_secrets

            # Look at what we did, clean up, and add it to git
            ls dev/*.enc
            rm dev/gpg_owner_trust dev/*.pgp
            git status
            git add dev/*.enc
            git add dev/public_gpg_key


### TEMPLATES ###
# Define common templates using YAML anchors


.cibuildwheel_template: &cibuildwheel_template
    stage: 
        build

    tags:
        # Tags define which runners will accept which jobs
        - linux
        - docker
        - privileged

    image: gitlab.kitware.com:4567/computer-vision/ci-docker/podman

    script:
        - podman --version
        - podman info --debug
        - python3 -m pip install git+https://github.com/Erotemic/cibuildwheel.git@dev/flow
        - pwd
        - ls -al
        - export CIBW_SKIP="pp* cp27-* cp35-*"
        - export CIBW_OCI_EXE="podman"
        # NOTE: this requires that some mechanism exists in cibuildwheel to
        # ignore this directory when it copys the repo into the container
        - mkdir -p ".cache/containers/vfs-storage/"
        - export CIBW_OCI_ROOT=$(realpath ".cache/containers/vfs-storage/")
        - echo "CIBW_OCI_ROOT = $CIBW_OCI_ROOT"
        - cibuildwheel --platform linux --print-build-identifiers
        # - cibuildwheel --output-dir wheelhouse --platform linux --archs x86_64,i686,aarch64,ppc64le,s390x,universal2,arm64,x86,AMD64
        - cibuildwheel --output-dir wheelhouse --platform linux
        - ls $CIBW_OCI_ROOT
        - ls wheelhouse

    artifacts:
        paths:
            - wheelhouse/

    # Contents of .cache/containers/vfs-storage are far too large to cache
    # Not sure if it is possible to cache the download of the images
    #cache:
    #    paths:
    #        - .cache/containers
    #    TODO: can we use skopeo to cache the images?

.common_template: &common_template
    tags:
        # Tags define which runners will accept which jobs
        - docker
        - linux
        - build

    variables:
        # Change pip's cache directory to be inside the project directory since we can
        # only cache local items.
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

    cache:
        paths:
            - .cache/pip
    
    
.test_full_template: &test_full_template
    <<: 
        - *common_template

    stage: 
        test

    before_script:
        # Setup the correct version of python on this manylinux instance
        - python --version  # Print out python version for debugging
        - python -m pip install virtualenv
        - python -m virtualenv venv
        - source venv/bin/activate
        # 
        - pip install pip -U
        - pip install setuptools -U
        - pip install -r requirements.txt -U
        - pip install opencv-python-headless

    script: 
        - echo "skipping tests for now"
        # FIXME: we should start from a docker iamge that already has LibGL setup
        - ls wheelhouse
        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
        - VERSION=$(python -c "import setup; print(setup.VERSION)")
        - BDIST_WHEEL_PATH=wheelhouse/kwimage-${VERSION}-${MB_PYTHON_TAG}-*manylinux*_x86_64.whl
        - pip install $BDIST_WHEEL_PATH
        - pip install pygments
        # - xdoctest kwimage --style=google all --mask 
        # Hack to test the installed wheel. TODO: make run_tests work better in this case.
        - mkdir -p foo && cd foo && pytest --cov-config ../.coveragerc --cov-report html --cov-report term --cov=kwimage --xdoc $(python -c "import ubelt; print(ubelt.modname_to_modpath('kwimage'))") ../tests
          
    # Coverage is a regex that will parse the coverage from the test stdout
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


.test_minimal_template: &test_minimal_template
    <<: 
        - *common_template

    stage: 
        test

    before_script:
        # Setup the correct version of python on this manylinux instance
        - python --version  # Print out python version for debugging
        - python -m pip install virtualenv
        - python -m virtualenv venv
        - source venv/bin/activate
        - pip install pip -U
        - pip install setuptools -U
        - pip install -r requirements/runtime.txt -U
        - pip install -r requirements/tests.txt -U
        - pip install opencv-python-headless
        #- pip install -r requirements/build.txt

    script: 
        - echo "skipping tests for now"
        # FIXME: we should start from a docker iamge that already has LibGL setup
        - ls wheelhouse
        - MB_PYTHON_TAG=py3-none-any
        - VERSION=$(python -c "import setup; print(setup.VERSION)")
        - BDIST_WHEEL_PATH=dist/kwimage-${VERSION}-${MB_PYTHON_TAG}.whl
        - pip install $BDIST_WHEEL_PATH
          #- xdoctest -m kwimage --style=google all
        - pip install pygments
        # Hack to test the installed wheel. TODO: make run_tests work better in this case.
        - export KWIMAGE_DISABLE_C_EXTENSIONS=1
        - pip install -r requirements/tests.txt
        - mkdir -p foo && cd foo && python -m pytest --cov-config ../.coveragerc --cov-report html --cov-report term --cov=kwimage --xdoc $(python -c "import ubelt; print(ubelt.modname_to_modpath('kwimage'))") ../tests
          
    # Coverage is a regex that will parse the coverage from the test stdout
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


gpgsign/wheels:
    <<: 
        - *common_template

    image:
        python:3.8

    stage: 
        gpgsign

    script: 
        - ls wheelhouse
        - ls dist
        - export GPG_EXECUTABLE=gpg
        - export GPG_KEYID=D297D757
        - $GPG_EXECUTABLE --version
        - openssl version
        - $GPG_EXECUTABLE --list-keys
        # note CI_KITWARE_SECRET is a protected variables only available on master and release branch
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GPG_SIGN_CMD="$GPG_EXECUTABLE --batch --yes --detach-sign --armor --local-user $GPG_KEYID"

        - |
            WHEEL_PATHS=(wheelhouse/*.whl)
            WHEEL_PATHS_STR=$(printf '"%s" ' "${WHEEL_PATHS[@]}")
            echo "$WHEEL_PATHS_STR"
            for WHEEL_PATH in "${WHEEL_PATHS[@]}"
            do
                echo "------"
                echo "WHEEL_PATH = $WHEEL_PATH"
                $GPG_SIGN_CMD --output $WHEEL_PATH.asc $WHEEL_PATH
                $GPG_EXECUTABLE --verify $WHEEL_PATH.asc $WHEEL_PATH  || echo "hack, the first run of gpg very fails"
                $GPG_EXECUTABLE --verify $WHEEL_PATH.asc $WHEEL_PATH 
            done
        - ls wheelhouse
        - ls dist

    artifacts:
        paths:
            - wheelhouse/*.asc

    only:
        refs:
            # Gitlab will only expose protected variables on protected branches
            # (which I've set to be master and release), so only run this stage
            # there.
            - master
            - release


deploy/wheels:
    <<: 
        - *common_template

    image:
        python:3.8

    stage: 
        deploy

    script: 
        - pip install six pyopenssl ndg-httpsclient pyasn1 requests[security] twine -U 
        - ls wheelhouse
        - ls dist
        - |
            WHEEL_PATHS=(wheelhouse/*.whl)
            WHEEL_PATHS_STR=$(printf '"%s" ' "${WHEEL_PATHS[@]}")
            echo "$WHEEL_PATHS_STR"
            for WHEEL_PATH in "${WHEEL_PATHS[@]}"
            do
                twine check $WHEEL_PATH.asc $WHEEL_PATH
                twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD $WHEEL_PATH.asc $WHEEL_PATH
            done
            
    only:
        refs:
            - release

### JOBS ###
# Define the actual jobs

# ---------------
# Python 3.9 Jobs

build/cp39-cp39-manylinux2010:
    <<: 
        - *cibuildwheel_template
    variables:
        CIBW_BUILD: "cp39-*"

test_full/cp39-cp39-manylinux2010:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.9

test_minimal/cp39-cp39-manylinux2010:
    <<: 
        - *test_minimal_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.9

# ---------------
# Python 3.8 Jobs

build/cp38-cp38-manylinux2010:
    <<: 
        - *cibuildwheel_template
    variables:
        CIBW_BUILD: "cp38-*"

test_full/cp38-cp38-manylinux2010:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8

test_minimal/cp38-cp38-manylinux2010:
    <<: 
        - *test_minimal_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.8

# ---------------
# Python 3.7 Jobs

build/cp37-cp37m-manylinux2010:
    <<: 
        - *cibuildwheel_template
    variables:
        CIBW_BUILD: "cp37-*"

test_full/cp37-cp37m-manylinux2010:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.7

test_minimal/cp37-cp37m-manylinux2010:
    <<: 
        - *test_minimal_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.7


# ---------------
# Python 3.6 Jobs

build/cp36-cp36m-manylinux2010:
    <<: 
        - *cibuildwheel_template
    variables:
        CIBW_BUILD: "cp36-*"

test_full/cp36-cp36m-manylinux2010:
    <<: 
        - *test_full_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.6

test_minimal/cp36-cp36m-manylinux2010:
    <<: 
        - *test_minimal_template
    image:
        gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.6


# ---------------
# Universal Python Jobs
build/py3-none-any:
    <<: 
        - *common_template

    stage: 
        build

    image: gitlab.kitware.com:4567/computer-vision/ci-docker/gl-python:3.7

    before_script:
        - python -V  # Print out python version for debugging
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install pip -U
        - pip install pip setuptools -U

    script: 
        - export KWIMAGE_DISABLE_C_EXTENSIONS=1
        - KWIMAGE_DISABLE_C_EXTENSIONS=1 python setup.py bdist_wheel
        - KWIMAGE_DISABLE_C_EXTENSIONS=1 python setup.py sdist
        - ls dist
        #- MB_PYTHON_TAG=py3-none-any
        #- # VERSION=$(python -c "import setup; print(setup.VERSION)")
        #- # BDIST_WHEEL_PATH=dist/kwimage-${VERSION}-${MB_PYTHON_TAG}.whl
        #- # pip install $BDIST_WHEEL_PATH
        #- # pip install pygments
        ## Hack to test the installed wheel. TODO: make run_tests work better in this case.
        #- # pip install -r requirements/tests.txt
        #- # mkdir -p foo && cd foo && python -m pytest --cov-config ../.coveragerc --cov-report html --cov-report term --cov=kwimage --xdoc $(python -c "import ubelt; print(ubelt.modname_to_modpath('kwimage'))") ../tests
        #- # xdoctest -m kwimage
          
    artifacts:
        paths:
            - dist/*.whl
    cache:
        paths:
            - .cache/pip


gpgsign/py3-none-any:
    <<: 
        - *common_template

    stage: 
        gpgsign

    script: 
        - ls dist
        - MB_PYTHON_TAG=py3-none-any
        - VERSION=$(python -c "import setup; print(setup.VERSION)")
        - BDIST_WHEEL_PATH=dist/kwimage-${VERSION}-${MB_PYTHON_TAG}.whl
        # Decrypt and import GPG Keys / trust
        - export GPG_EXECUTABLE=gpg
        - export GPG_KEYID=D297D757
        - $GPG_EXECUTABLE --version
        - openssl version
        - $GPG_EXECUTABLE --list-keys
        # note CI_KITWARE_SECRET is a protected variables only available on master and release branch
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GPG_SIGN_CMD="$GPG_EXECUTABLE --batch --yes --detach-sign --armor --local-user $GPG_KEYID"
        #- # $GPG_EXECUTABLE --list-keys
        - echo "Signing wheels"
        - $GPG_SIGN_CMD --output $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
        - ls dist
        - echo "Verifying wheels"
        - $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH  || echo "hack, the first run of gpg very fails"
        - $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH 
        - echo "Verified wheels"

    artifacts:
        paths:
            - dist/*.asc

    only:
        refs:
            # Gitlab will only expose protected variables on protected branches
            # (which I've set to be master and release), so only run this stage
            # there.
            - master
            - release
    image:
        python:3.7

deploy/py3-none-any:
    <<: 
        - *common_template

    image:
        python:3.7

    stage: 
        deploy

    script: 
        - ls dist
        - MB_PYTHON_TAG=py3-none-any
        - VERSION=$(python -c "import setup; print(setup.VERSION)")
        - BDIST_WHEEL_PATH=dist/kwimage-${VERSION}-${MB_PYTHON_TAG}.whl
        - pip install six pyopenssl ndg-httpsclient pyasn1 -U 
        - pip install requests[security] twine 
        - echo "Checking wheels"
        - ls -al ${BDIST_WHEEL_PATH}*
        - twine check $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
        - echo "Uploading wheels"
        # todo, can we tag the branch here as well?
        # note TWINE_USERNAME and TWINE_PASSWORD are protected variables only available on master and release branch
        - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
        # Have the server git-tag the release and push the tags
        - VERSION=$(python -c "import setup; print(setup.VERSION)")
        # do sed twice to handle the case of https clone with and without a read token
        - URL_HOST=$(git remote get-url origin | sed -e 's|https\?://.*@||g' | sed -e 's|https\?://||g')
        - echo "URL_HOST = $URL_HOST"
        - git config user.email "ci@gitlab.kitware.com"
        - git config user.name "Gitlab-CI"
        - git tag $VERSION -m "tarball tag $VERSION"
        - git push --tags "https://${GIT_PUSH_TOKEN}@${URL_HOST}"
            
    only:
        refs:
            - release


.__local_docker_heredoc__:
        - | 
            docker run -it python:3.8 bash

            cd $HOME
            git clone https://gitlab.kitware.com/computer-vision/kwarray.git
            cd $HOME/kwarray
            git checkout dev/0.5.10

            python -V  # Print out python version for debugging
            export PYVER=$(python -c "import sys; print('{}{}'.format(*sys.version_info[0:2]))")
            pip install virtualenv
            virtualenv venv$PYVER
            source venv$PYVER/bin/activate
            pip install pip -U
            pip install pip setuptools -U
            python -V  # Print out python version for debugging
            pip install -e .


            cd $HOME
            git clone https://gitlab.kitware.com/computer-vision/kwimage.git

            # python setup.py bdist_wheel --universal

            python -V  # Print out python version for debugging
            export PYVER=$(python -c "import sys; print('{}{}'.format(*sys.version_info[0:2]))")
            pip install virtualenv
            virtualenv venv$PYVER
            source venv$PYVER/bin/activate
            pip install pip -U
            pip install pip setuptools -U
            python -V  # Print out python version for debugging
            pip install .[tests]

            xdoctest -m kwimage.structs.boxes all
            
            ./run_doctests.sh
            ./run_tests.py
