# Note: expand yaml
# yaml merge-expand .gitlab-ci.yml _expandyml && cat _expandyml
# curl --header "Content-Type: application/json" https://gitlab.com/api/v4/ci/lint --data "$(cat .gitlab-ci.yml)"


### TEMPLATES ###
# Define common templates using YAML anchors

stages:
  - build
  - test
  - gpgsign
  - deploy

.common_template: &common_template
    tags:
        # Tags define which runners will accept which jobs
        - docker
        - linux

    variables:
        # Change pip's cache directory to be inside the project directory since we can
        # only cache local items.
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/mb_work/cache_pip"
    
    
.multibuild_template: &multibuild_template
    <<: 
        - *common_template

    stage: 
        build

    image: quay.io/pypa/manylinux2010_x86_64

    script: 
        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
        - ls
        - MB_PYTHON_TAG=$MB_PYTHON_TAG _INSIDE_DOCKER=YES ./run_multibuild.sh

    artifacts:
        paths:
            - wheelhouse/*.whl


.test_template: &test_template
    <<: 
        - *common_template

    stage: 
        test

    before_script:
        # Setup the correct version of python on this manylinux instance
        - python --version  # Print out python version for debugging
        - python -m pip install virtualenv
        - python -m virtualenv venv
        - source venv/bin/activate
        # 
        - pip install pip -U
        - pip install pip setuptools -U
        - pip install -r requirements.txt

    script: 
        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
        - ls wheelhouse
        - pip install wheelhouse/kwimage*-${MB_PYTHON_TAG}-manylinux2010_x86_64.whl 
        - xdoctest -m kwimage
        - pip install pygments
        # Hack to test the installed wheel. TODO: make run_tests work better in this case.
        - mkdir -p foo && cd foo && pytest --cov-config ../.coveragerc --cov-report html --cov-report term --cov=kwimage --xdoc $(python -c "import ubelt; print(ubelt.modname_to_modpath('kwimage'))") ../tests
          
    # Coverage is a regex that will parse the coverage from the test stdout
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'


.gpgsign_template: &gpgsign_template
    <<: 
        - *common_template

    stage: 
        gpgsign

    script: 
        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
        - ls wheelhouse
        - BDIST_WHEEL_PATH=wheelhouse/kwimage*-${MB_PYTHON_TAG}-manylinux2010_x86_64.whl
        - echo "WRTIE AND EXECUTE THE PUBLISH SCRIPT"
        - | 
            __heredoc__='''
            # Load or generate secrets
            source $(secret_loader.sh)
            echo $CI_KITWARE_SECRET
            echo $TWINE_USERNAME

            # encrypt relevant travis variables
            # ADD RELEVANT VARIABLES TO GITLAB SECRET VARIABLES
            # https://gitlab.kitware.com/computer-vision/kwimage/-/settings/ci_cd
            #gitlab encrypt CI_KITWARE_SECRET=$CI_KITWARE_SECRET
            #gitlab encrypt TWINE_PASSWORD=$TWINE_PASSWORD  
            #gitlab encrypt TWINE_USERNAME=$TWINE_USERNAME 

            # HOW TO ENCRYPT YOUR SECRET GPG KEY
            IDENTIFIER="travis-ci-Erotemic"
            GPG_KEYID=$(gpg --list-keys --keyid-format LONG "$IDENTIFIER" | head -n 2 | tail -n 1 | awk '{print $1}' | tail -c 9)
            echo "GPG_KEYID = $GPG_KEYID"

            # Export plaintext gpg public keys, private keys, and trust info
            mkdir -p dev
            gpg --armor --export-secret-keys $GPG_KEYID > dev/ci_secret_gpg_key.pgp
            gpg --armor --export $GPG_KEYID > dev/ci_public_gpg_key.pgp
            gpg --export-ownertrust > dev/gpg_owner_trust

            # Encrypt gpg keys and trust with travis secret
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/ci_public_gpg_key.pgp > dev/ci_public_gpg_key.pgp.enc
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/ci_secret_gpg_key.pgp > dev/ci_secret_gpg_key.pgp.enc
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -e -a -in dev/gpg_owner_trust > dev/gpg_owner_trust.enc

            # Test decrpyt
            GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc

            source $(secret_unloader.sh)

            # Look at what we did, clean up, and add it to git
            ls dev/*.enc
            rm dev/gpg_owner_trust dev/*.pgp
            git status
            git add dev/*.enc

            '''  # <hack vim "regex" parser> '
        # Decrypt and import GPG Keys / trust
        - GPG_EXECUTABLE=gpg
        - GPG_KEYID=D297D757
        - $GPG_EXECUTABLE --version
        - openssl version
        - $GPG_EXECUTABLE --list-keys
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_public_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/gpg_owner_trust.enc | $GPG_EXECUTABLE --import-ownertrust
        - GLKWS=$CI_KITWARE_SECRET openssl enc -aes-256-cbc -pbkdf2 -md SHA512 -pass env:GLKWS -d -a -in dev/ci_secret_gpg_key.pgp.enc | $GPG_EXECUTABLE --import 
        - $GPG_EXECUTABLE --list-keys
        - | 
            echo "Signing wheels"
            GPG_SIGN_CMD="$GPG_EXECUTABLE --batch --yes --detach-sign --armor --local-user $GPG_KEYID"
            $GPG_SIGN_CMD --output $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
        - | 
            echo "Verifying wheels"
            $GPG_EXECUTABLE --verify $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH 

    artifacts:
        paths:
            - wheelhouse/*.asc


.deploy_template: &deploy_template
    <<: 
        - *common_template

    stage: 
        deploy

    script: 
        - MB_PYTHON_TAG=$(echo ${CI_JOB_NAME} | sed 's/.*\/\(.*\)-manylinux2010/\1/')
        - BDIST_WHEEL_PATH=wheelhouse/kwimage*-${MB_PYTHON_TAG}-manylinux2010_x86_64.whl
        - pip install six pyopenssl ndg-httpsclient pyasn1 -U --user
        - pip install requests[security] twine --user
        - | 
            echo "Checking wheels"
            twine check $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
        - | 
            echo "Uploading wheels"
            # todo, can we tag the branch here as well?
            twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD --sign $BDIST_WHEEL_PATH.asc $BDIST_WHEEL_PATH
            
    only:
        refs:
            - release

### JOBS ###
# Define the actual jobs


# ---------------
# Python 3.7 Jobs

build/cp37-cp37m-manylinux2010:
    <<: 
        - *multibuild_template

test/cp37-cp37m-manylinux2010:
    <<: 
        - *test_template
    image:
        python:3.7

gpgsign/cp37-cp37m-manylinux2010:
    <<: 
        - *gpgsign_template
    image:
        python:3.7

deploy/cp37-cp37m-manylinux2010:
    <<: 
        - *deploy_template
    image:
        python:3.7


# ---------------
# Python 3.6 Jobs

build/cp36-cp36m-manylinux2010:
    <<: 
        - *multibuild_template

test/cp36-cp36m-manylinux2010:
    <<: 
        - *test_template
    image:
        python:3.6

gpgsign/cp36-cp36m-manylinux2010:
    <<: 
        - *gpgsign_template
    image:
        python:3.6

deploy/cp36-cp36m-manylinux2010:
    <<: 
        - *deploy_template
    image:
        python:3.6


# ---------------
# Python 3.5 Jobs

build/cp35-cp35m-manylinux2010:
    <<: 
        - *multibuild_template

test/cp35-cp35m-manylinux2010:
    <<: 
        - *test_template
    image:
        python:3.5

gpgsign/cp35-cp35m-manylinux2010:
    <<: 
        - *gpgsign_template
    image:
        python:3.5

deploy/cp35-cp35m-manylinux2010:
    <<: 
        - *deploy_template
    image:
        python:3.5


# ---------------
# Python 2.7 Jobs

build/cp27-cp27mu-manylinux2010:
    <<: 
        - *multibuild_template

test/cp27-cp27mu-manylinux2010:
    <<: 
        - *test_template
    image:
        python:2.7

gpgsign/cp27-cp27mu-manylinux2010:
    <<: 
        - *gpgsign_template
    image:
        python:2.7

deploy/cp27-cp27mu-manylinux2010:
    <<: 
        - *deploy_template
    image:
        python:2.7
