### TEMPLATES ###
# Define common templates using YAML anchors

.common_template: &common_template
    tags:
        # Tags define which runners will accept which jobs
        - docker
        - linux

.build_test_template: &build_test_template
    <<: 
        - *common_template

    image: quay.io/pypa/manylinux2010_x86_64

    before_script:
        # Setup the correct version of python on this manylinux instance
        - echo "PY_DPATH = $PY_DPATH"
        - export PATH=/opt/python/$PY_DPATH/bin:$PATH
        - export LD_LIBRARY_PATH=/opt/python/$PY_DPATH/lib:$PATH
        - export CPATH=/opt/python/$PY_DPATH/include:$PATH
        - which python
        - python -V  # Print out python version for debugging
        - pip install virtualenv
        - virtualenv venv
        - source venv/bin/activate
        - pip install pip -U
        - pip install pip setuptools -U
        - pip install -r requirements.txt

    script: 
        # Setup the correct version of python on this manylinux instance
        - #export PATH=/opt/python/$PY_DPATH/bin:$PATH
        - #export LD_LIBRARY_PATH=/opt/python/$PY_DPATH/lib:$PATH
        - #export CPATH=/opt/python/$PY_DPATH/include:$PATH
        - python setup.py develop
        - ./run_tests.py

    # Coverage is a regex that will parse the coverage from the test stdout
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

    #variables:
    #    # Change pip's cache directory to be inside the project directory since we can
    #    # only cache local items.
    #    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

    cache:
        paths:
            - .cache/pip
            - venv/

    artifacts:
        paths:
            - dist/*.whl

.deploy_template: &deploy_template

    script:
        - python bdist_wheel
    #sudo apt update
    #sudo apt install snapd
    #sudo snap install patchelf --edge --classic
      


### JOBS ###
# Define the actual jobs

build:python2.7:
    <<: 
        - *build_test_template

    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        PY_DPATH: cp27-27m


build:python3.5:
    <<: 
        - *build_test_template

    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        PY_DPATH: cp35-cp35m


build:python3.6:
    <<: 
        - *build_test_template

    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        PY_DPATH: cp36-cp36m


build:python3.7:
    <<: 
        - *build_test_template

    variables:
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        PY_DPATH: cp37-cp37m
